[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "zsvc"
author = "Zahari Kassabov"
author-email = "zahari.kassabov@cern.ch"
home-page = "https://github.com/Zaharid/zsvc"
classifiers = ["License :: OSI Approved :: MIT License"]

